### ISSUE TITLE
I can't build this

### ISSUE THREAD

**Issue by QuintenQVD0** [sachingorkar102/Cosmin#1]
Hi
I am trying to build your plugin with github actions. I Created a fork and made a worker file. I let it download all server spigot jars and then give the command to build it. But is spit out some errors.  I tryed java 8 , 11 ,16 all don't work. 

my error: https://pastebin.com/S7kNc53u  
my worker file: https://pastebin.com/YmrZzY8C --> it fails on the build everyting.

what am I doning wrong?

**Comment by sachingorkar102** [comment]
I don't know much about github actions sorry ^^

**Comment by QuintenQVD0** [comment]
It just create a docker container and execute the commands you give it
i make the libs directory and download all jars in it. then i run the maven build command. its the same as i you do it on your local machine. But its not working. what java do you use and do gou get any off this typ off errors or what is your build command?

**Comment by QuintenQVD0** [comment]
i Fixt it it can't build on github actions becouse you use plexus-compiler-eclipse

**Comment by sachingorkar102** [comment]
Congratulations
