### ISSUE TITLE
Multiverse armor and off-hand slot kept/transferred between worlds

### ISSUE THREAD

**Issue by tyepavitt** [sachingorkar102/Cosmin#3]
Found a bug where my armor and off-hand slot items are kept/transferred from my survival world to my hub world. It only happens if I set my default spawn point to the hub in essentials, teleport to my survival world, put on armor, leave the server and join back to the hub.

If I teleport to the survival world, put on armor and then teleport to the hub without disconnecting, my items are only kept/transfered for a few seconds before they are cleared.

**Comment by sachingorkar102** [comment]
Did you checked weather the armor is real or not by clicking on it?

**Comment by sachingorkar102** [comment]
Also can you make a video showing the bug?

**Comment by tyepavitt** [comment]
When I click on the armor everything updates and gets cleared

Here's the video showing the bug: https://www.youtube.com/watch?v=KKCHGk1JrJU

**Comment by sachingorkar102** [comment]
The video seems unavailable 
Also if armor disappears then it should be fine

**Comment by tyepavitt** [comment]
> The video seems unavailable Also if armor disappears then it should be fine

Does the youtube video work now?

**Comment by sachingorkar102** [comment]
hmm weird, but the armor is not actually there tho

**Comment by sachingorkar102** [comment]
oops accidently closed it

**Comment by tyepavitt** [comment]
Just downloaded the new update and it works properly now! Thank you so much!
