### ISSUE TITLE
How do i build this 

### ISSUE THREAD

**Issue by QuintenQVD0** [sachingorkar102/Cosmin#4]
i continus get error  Failed to execute goal on project nms1_18: Could not resolve dependencies for project com.github.sachin.cosmin:nms1_18:jar:2.4: Could not find artifact org.spigotmc:spigot:jar:remapped-mojang:1.18-R0.1-SNAPSHOT

i downloaded it from here: https://maven.elmakers.com/repository/org/spigotmc/spigot/1.18-R0.1-SNAPSHOT/ but where must i set the file and what should it be named?

**Comment by sachingorkar102** [comment]
Plugin is open source for reference purposes only, i can't guide you on how to build it
(You have to build the remapped jar yourself using buildtools)

**Comment by QuintenQVD0** [comment]
ok thanks for your help i will build them using buildtools but where do i need to enter the hashCode because i get a error Object.hashCode()" because "key" is null and where and how should i generate a hash and off what type?
